### ISSUE TITLE
kubectl run to create deployment has been deprecated

### ISSUE THREAD

**Issue by supirman** [GoogleCloudPlatform/gke-logging-sinks-demo#39]
There is [.tf that use kubectl run to create a deployment](https://github.com/GoogleCloudPlatform/gke-logging-sinks-demo/blob/dc5cfc0b33f20a54638dcabbd78fe171fd711679/terraform/main.tf#L91). 
This will create pods instead of deployment, [the old functionality has been deprecated](https://github.com/kubernetes/kubernetes/pull/87077).

**Comment by elkyee** [comment]
Updated kubectl commands for deployment and worked.

provisioner "local-exec" {
    command = "kubectl --namespace default create deployment hello-server --image gcr.io/google-samples/hello-app:1.0"
  }

  provisioner "local-exec" {
    command = "kubectl --namespace default expose deployment hello-server --type \"LoadBalancer\" --port=8080"
  }
